import { CharacterProps } from '@/types/character';

// Characteristics:
// - dominion: Leaders and those seeking power/control
// - popularity: Social media stars and celebrities
// - attractiveness: Charismatic and influential personalities
// - richness: Wealthy entrepreneurs and business moguls

// Color schemes:
// dominion: gold/yellow (#ffff0f)
// popularity: blue (#0ffcff)
// attractiveness: red (#ff0f0f)
// richness: green (#0fff0f)

// Background images:
// /backgrounds/park.jpeg - Outdoor/nature scenes
// /backgrounds/home.jpg - Interior/home settings
// /backgrounds/room.jpeg - Office/work environments
// /backgrounds/library.jpg - Study/knowledge settings

const characters: CharacterProps[] = [
	{
		number: '001',
		name: 'Tom Kook',
		firstname: 'Tom',
		lastname: 'Kook',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card24.png',
		srcFrontBg: '/backgrounds/home.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '002',
		name: 'Povel Durev',
		firstname: 'Povel',
		lastname: 'Durev',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card23.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '003',
		name: 'Steve Jops',
		firstname: 'Steve',
		lastname: 'Jops',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card18.png',
		srcFrontBg: '/backgrounds/attractiveness.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '004',
		name: 'Marc Sugarberg',
		firstname: 'Marc',
		lastname: 'Sugarberg',
		characteristic: 'richness',
		srcFront: '/characters/middle/card34.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '005',
		name: 'Sergey Green',
		firstname: 'Sergey',
		lastname: 'Green',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card28.png',
		srcFrontBg: '/backgrounds/library.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '006',
		name: 'LebrOne James',
		firstname: 'LebrOne',
		lastname: 'James',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card17.png',
		srcFrontBg: '/backgrounds/night-city.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '007',
		name: 'Sam Aitman',
		firstname: 'Sam',
		lastname: 'Aitman',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card35.png',
		srcFrontBg: '/backgrounds/home.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '008',
		name: 'Larry Sage',
		firstname: 'Larry',
		lastname: 'Sage',
		characteristic: 'richness',
		srcFront: '/characters/middle/card11.png',
		srcFrontBg: '/backgrounds/dominion-city.jpg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '009',
		name: 'Divine Johnzon',
		firstname: 'Divine',
		lastname: 'Johnzon',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card37.png',
		srcFrontBg: '/backgrounds/room.jpeg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '010',
		name: 'Madronna',
		firstname: 'Madronna',
		lastname: 'Madronna',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card15.png',
		srcFrontBg: '/backgrounds/dominion-city.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '011',
		name: 'Patrick Makhomes',
		firstname: 'Patrick',
		lastname: 'Makhomes',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card14.png',
		srcFrontBg: '/backgrounds/home.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '012',
		name: 'Michael BloomBig',
		firstname: 'Michael',
		lastname: 'BloomBig',
		characteristic: 'richness',
		srcFront: '/characters/middle/card30.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '013',
		name: 'Opra Winfred',
		firstname: 'Opra',
		lastname: 'Winfred',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card12.png',
		srcFrontBg: '/backgrounds/night-building.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '014',
		name: 'Emma Vatson',
		firstname: 'Emma',
		lastname: 'Vatson',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card21.png',
		srcFrontBg: '/backgrounds/room.jpeg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '015',
		name: 'Elan Mosk',
		firstname: 'Elan',
		lastname: 'Mosk',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card01.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '016',
		name: 'Jeff Besos',
		firstname: 'Jeff',
		lastname: 'Besos',
		characteristic: 'richness',
		srcFront: '/characters/middle/card36.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '017',
		name: 'Satoshi Hellomoto',
		firstname: 'Satoshi',
		lastname: 'Hellomoto',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card03.png',
		srcFrontBg: '/backgrounds/night-city.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '018',
		name: 'Lion Messiah',
		firstname: 'Lion',
		lastname: 'Messiah',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card13.png',
		srcFrontBg: '/backgrounds/popularity.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '019',
		name: 'Kim Kong-fun',
		firstname: 'Kim',
		lastname: 'Kong-fun',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card02.png',
		srcFrontBg: '/backgrounds/attractiveness.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '020',
		name: 'Christian Penaldo',
		firstname: 'Christian',
		lastname: 'Penaldo',
		characteristic: 'richness',
		srcFront: '/characters/middle/card09.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '021',
		name: 'Chaquira',
		firstname: 'Chaquira',
		lastname: 'Chaquira',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card32.png',
		srcFrontBg: '/backgrounds/home.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '022',
		name: 'Hack Ma',
		firstname: 'Hack',
		lastname: 'Ma',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card16.png',
		srcFrontBg: '/backgrounds/popularity.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '023',
		name: 'Charleez Tiron',
		firstname: 'Charleez',
		lastname: 'Tiron',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card25.png',
		srcFrontBg: '/backgrounds/game-bg.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '024',
		name: 'Papa Frank',
		firstname: 'Papa',
		lastname: 'Frank',
		characteristic: 'richness',
		srcFront: '/characters/middle/card20.png',
		srcFrontBg: '/backgrounds/dominion-city.jpg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '025',
		name: 'Tim Brody',
		firstname: 'Tim',
		lastname: 'Brody',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card29.png',
		srcFrontBg: '/backgrounds/library.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '026',
		name: 'Jackie Chwan',
		firstname: 'Jackie',
		lastname: 'Chwan',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card26.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '027',
		name: 'Ariadna Grant',
		firstname: 'Ariadna',
		lastname: 'Grant',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card33.png',
		srcFrontBg: '/backgrounds/attractiveness.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '028',
		name: 'Buff Warrant',
		firstname: 'Buff',
		lastname: 'Warrant',
		characteristic: 'richness',
		srcFront: '/characters/middle/card27.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '029',
		name: 'Ursula Fonder Line',
		firstname: 'Ursula',
		lastname: 'Fonder Line',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card05.png',
		srcFrontBg: '/backgrounds/night-building.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '030',
		name: 'Steven Kong',
		firstname: 'Steven',
		lastname: 'Kong',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card06.png',
		srcFrontBg: '/backgrounds/dominion-class.jpeg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '031',
		name: 'Margo Robo',
		firstname: 'Margo',
		lastname: 'Robo',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card38.png',
		srcFrontBg: '/backgrounds/attractiveness.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '032',
		name: 'Bill Mates',
		firstname: 'Bill',
		lastname: 'Mates',
		characteristic: 'richness',
		srcFront: '/characters/middle/card31.png',
		srcFrontBg: '/backgrounds/dominion-city.jpg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '033',
		name: 'Scarlit Yohansen',
		firstname: 'Scarlit',
		lastname: 'Yohansen',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card08.png',
		srcFrontBg: '/backgrounds/park.jpeg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '034',
		name: 'Selene Gomes',
		firstname: 'Selene',
		lastname: 'Gomes',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card07.png',
		srcFrontBg: '/backgrounds/popularity.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '035',
		name: 'Irena Shayk',
		firstname: 'Irena',
		lastname: 'Shayk',
		characteristic: 'attractiveness',
		srcFront: '/characters/middle/card19.png',
		srcFrontBg: '/backgrounds/dominion.jpg',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#ff0f0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '036',
		name: 'Vitaly Bulletin',
		firstname: 'Vitaly',
		lastname: 'Bulletin',
		characteristic: 'richness',
		srcFront: '/characters/middle/card04.png',
		srcFrontBg: '/backgrounds/room.jpeg',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '037',
		name: 'Ri Anna',
		firstname: 'Ri',
		lastname: 'Anna',
		characteristic: 'dominion',
		srcFront: '/characters/middle/card10.png',
		srcFrontBg: '/backgrounds/dominion-city.jpg',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: '038',
		name: 'Billie Stylish',
		firstname: 'Billie',
		lastname: 'Stylish',
		characteristic: 'popularity',
		srcFront: '/characters/middle/card22.png',
		srcFrontBg: '/backgrounds/night-city.jpg',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		srcBack: '',
		body: "I'm glad the game works on Telegram",
	},
];

export default characters;
